# Generated by Django 2.1.3 on 2018-12-14 05:32

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='DataCenter',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=256)),
                ('site', models.CharField(max_length=256)),
                ('contact', models.CharField(max_length=256)),
                ('phone', models.CharField(max_length=11)),
                ('email', models.EmailField(max_length=254)),
                ('other_info', models.TextField()),
            ],
            options={
                'db_table': 'datacenter',
            },
        ),
    ]
