# Generated by Django 2.1.3 on 2018-12-14 05:33

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('datacenter', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='datacenter',
            name='other_info',
            field=models.TextField(null=True),
        ),
    ]
