# Generated by Django 2.1.3 on 2018-12-14 07:12

from django.db import migrations, models
import django.utils.timezone


class Migration(migrations.Migration):

    dependencies = [
        ('datacenter', '0002_auto_20181214_1333'),
    ]

    operations = [
        migrations.AddField(
            model_name='datacenter',
            name='created',
            field=models.DateTimeField(auto_now_add=True, default=django.utils.timezone.now),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='datacenter',
            name='updated',
            field=models.DateTimeField(auto_now=True),
        ),
    ]
