# Generated by Django 2.1.3 on 2018-12-14 08:25

from django.db import migrations, models
import django.utils.timezone


class Migration(migrations.Migration):

    dependencies = [
        ('datacenter', '0004_token'),
    ]

    operations = [
        migrations.DeleteModel(
            name='Token',
        ),
        migrations.AddField(
            model_name='datacenter',
            name='token',
            field=models.TextField(default=django.utils.timezone.now),
            preserve_default=False,
        ),
    ]
