# Generated by Django 2.1.3 on 2018-12-14 07:12

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('datacenter', '0003_auto_20181214_1512'),
    ]

    operations = [
        migrations.CreateModel(
            name='Host',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('hostname', models.CharField(max_length=256)),
                ('ip', models.TextField(null=True)),
                ('cpu', models.TextField(null=True)),
                ('memory', models.TextField(null=True)),
                ('motherboard', models.TextField(null=True)),
                ('disk', models.TextField(null=True)),
                ('gpu', models.TextField(null=True)),
                ('dns', models.TextField(null=True)),
                ('virtual_host', models.BooleanField(default=False)),
                ('physical_host', models.TextField(null=True)),
                ('service', models.TextField(null=True)),
                ('machine_room', models.TextField(null=True)),
                ('cabinet', models.TextField(null=True)),
                ('created', models.DateTimeField(auto_now_add=True)),
                ('updated', models.DateTimeField(auto_now=True)),
                ('datacenter', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='datacenter.DataCenter')),
            ],
            options={
                'db_table': 'host',
            },
        ),
        migrations.CreateModel(
            name='HostTag',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=10)),
                ('color', models.CharField(max_length=10)),
                ('host_list', models.TextField(null=True)),
                ('datacenter', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='datacenter.DataCenter')),
            ],
            options={
                'db_table': 'hosttag',
            },
        ),
    ]
